sudo: true
language: c
os:
  - linux
compiler:
  - gcc
env:
  - MPI_IMPL=mpich
before_install:
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade autoconf
  - sh ./travis/install-deps.sh $MPI_IMPL
script:
  - sh ./travis/build-run.sh $MPI_IMPL
after_failure:
  - cat ./config.log
  - cat ./test-suite.log
  - find . -name "*.log" -exec head -n 100 {} ";"
